project_id = "wcdtdjztzrlvwkmlwpgw"

[functions.generate-search-embedding]
verify_jwt = true

[functions.ask-knowledge]
verify_jwt = true

[functions.find-quote]
verify_jwt = true

[functions.find-image]
verify_jwt = true
