project_id = "wcdtdjztzrlvwkmlwpgw"

[functions.generate-search-embedding]
verify_jwt = true

[functions.ask-knowledge]
verify_jwt = true

[functions.find-quote]
verify_jwt = true

[functions.find-image]
verify_jwt = true

[functions.process-action]
verify_jwt = false

[functions.post-to-slack]
verify_jwt = true
